services:
  celery_worker:
    build: .
    container_name: celery_worker
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"
